Take-Home Assignment

Solve the following problems.

Part 1 - Numpy

Use this dataset for the first 4 questions.

In [3]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.



In [7]:
A=np.random.randint(1,10,size=10)
B=np.random.randint(2,20,size=10)
new_array_1=np.vstack((A,B))
new_array_2=np.hstack((A,B))
print(f"new array 1:{new_array_1}")
print(f"new array 2:{new_array_2}")

new array 1:[[ 9  2  8  2  2  1  7  2  4  6]
 [ 2  6 15 19 15 10 10 10 19  2]]
new array 2:[ 9  2  8  2  2  1  7  2  4  6  2  6 15 19 15 10 10 10 19  2]


2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]



In [8]:
common_elements = np.intersect1d(A,B)
common_elements

array([2, 6])

3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]


In [9]:
needed= np.where((A>5) &(A<10))
needed

(array([0, 2, 6, 9]),)


4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [18]:
now= np.where((iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0))

In [20]:
iris_2d[now]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## pandas


1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [22]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head(5)

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [27]:
df.iloc[0]

Manufacturer                  Acura
Model                       Integra
Type                          Small
Min.Price                      12.9
Price                          15.9
Max.Price                      18.8
MPG.city                       25.0
MPG.highway                    31.0
AirBags                         NaN
DriveTrain                    Front
Cylinders                         4
EngineSize                      1.8
Horsepower                    140.0
RPM                          6300.0
Rev.per.mile                 2890.0
Man.trans.avail                 Yes
Fuel.tank.capacity             13.2
Passengers                      5.0
Length                        177.0
Wheelbase                     102.0
Width                          68.0
Turn.circle                    37.0
Rear.seat.room                 26.5
Luggage.room                    NaN
Weight                       2705.0
Origin                      non-USA
Make                  Acura Integra
Name: 0, dtype: object

In [35]:
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [37]:
# new_df=pd.DataFrame(columns=['Manufacturer', 'Model', 'Type'])
# print(f"initial new df:{new_df}")
# for i in range(0,len(df),20):
#   curr=pd.DataFrame([{'Manufacturer':df.iloc[i]['Manufacturer'], 'Model':df.iloc[i]['Model'], 'Type':df.iloc[i]['Type']}])
#   new_df=pd.concat((new_df,df.iloc[i]))
# new_df

df[['Manufacturer','Model','Type']].iloc[::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.


In [39]:
df.fillna(df['Min.Price'].mean())
df.fillna(df['Max.Price'].mean())

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1     21.459091   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  21.459091   37.7  44.600000      19.0   
4           BMW     535i  Midsize  21.459091   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92    21.459091      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0           21.459091      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger  21.459091  ...        6.0   193.0   
4          30.0           21.459091       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0           21.459091      Front  ...        7.0   187.0   
89         30.0           21.459091      Front  ...        5.0   180.0   
90         25.0           21.459091      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     21.459091  2705.0   
1       115.0  71.000000         38.0           30.0     15.000000  3560.0   
2       102.0  67.000000         37.0           28.0     14.000000  3375.0   
3       106.0  21.459091         37.0           31.0     17.000000  3405.0   
4       109.0  69.000000         39.0           27.0     13.000000  3640.0   
..        ...        ...          ...            ...           ...     ...   
88      115.0  72.000000         38.0           34.0     21.459091  3960.0   
89      103.0  67.000000         35.0           31.5     14.000000  2985.0   
90       97.0  66.000000         36.0           26.0     15.000000  2810.0   
91      104.0  67.000000         37.0           29.5     14.000000  2985.0   
92      105.0  69.000000         38.0           30.0     15.000000  3245.0   

       Origin                Make  
0     non-USA       Acura Integra  
1     non-USA        Acura Legend  
2     non-USA             Audi 90  
3     non-USA            Audi 100  
4     non-USA            BMW 535i  
..        ...                 ...  
88  21.459091  Volkswagen Eurovan  
89    non-USA   Volkswagen Passat  
90    non-USA  Volkswagen Corrado  
91    non-USA           Volvo 240  
92    non-USA           Volvo 850  

[93 rows x 27 columns]

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

In [40]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [54]:
df.head(10)

0   1   2   3  row_sum
0  10  28  29  25    637.0
1  18  25  11  10    565.0
2  13  14  28  36    711.0
3  35  17  33  29    715.0
4  23  35  33  31    366.0
5  32  22  38  24    348.0
6  30  30  39  32    393.0
7  14  19  11  31    225.0
8  31  39  39  39    444.0
9  30  19  32  11    276.0

In [56]:
df['row_sum']=df.sum(axis=1)
df

0   1   2   3  row_sum
0   10  28  29  25       92
1   18  25  11  10       64
2   13  14  28  36       91
3   35  17  33  29      114
4   23  35  33  31      122
5   32  22  38  24      116
6   30  30  39  32      131
7   14  19  11  31       75
8   31  39  39  39      148
9   30  19  32  11       92
10  18  24  33  32      107
11  29  30  39  12      110
12  16  23  14  17       70
13  29  27  36  33      125
14  33  21  23  11       88